// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5NvdUnyfgv24GDchoubMUpSokdNdOCo',
    appId: '1:612289261776:web:7992cf7d6d42fa1365aed5',
    messagingSenderId: '612289261776',
    projectId: 'liga-app-18rapp',
    authDomain: 'liga-app-18rapp.firebaseapp.com',
    storageBucket: 'liga-app-18rapp.firebasestorage.app',
    measurementId: 'G-6Q0QK0WT03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVLywm80Az0Rf2sfW3WChOtGFKsA9cCPA',
    appId: '1:612289261776:android:e0539e32969f6cd865aed5',
    messagingSenderId: '612289261776',
    projectId: 'liga-app-18rapp',
    storageBucket: 'liga-app-18rapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1M6XIZgsTAezwGxAiSMNaxYynxWpiKH0',
    appId: '1:612289261776:ios:9f79d91fb515de6065aed5',
    messagingSenderId: '612289261776',
    projectId: 'liga-app-18rapp',
    storageBucket: 'liga-app-18rapp.firebasestorage.app',
    iosBundleId: 'com.example.tuLigaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1M6XIZgsTAezwGxAiSMNaxYynxWpiKH0',
    appId: '1:612289261776:ios:9f79d91fb515de6065aed5',
    messagingSenderId: '612289261776',
    projectId: 'liga-app-18rapp',
    storageBucket: 'liga-app-18rapp.firebasestorage.app',
    iosBundleId: 'com.example.tuLigaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE5NvdUnyfgv24GDchoubMUpSokdNdOCo',
    appId: '1:612289261776:web:98b178e96574a3af65aed5',
    messagingSenderId: '612289261776',
    projectId: 'liga-app-18rapp',
    authDomain: 'liga-app-18rapp.firebaseapp.com',
    storageBucket: 'liga-app-18rapp.firebasestorage.app',
    measurementId: 'G-PFZGK3454F',
  );
}
